export type Question = {
  id: number
  konu: string
  soru: string
  secenekler: string[]
  dogru: number // index of correct answer
}

// Notlardan üretilen soru bankası. Her soru not içindeki bir bilgiye dayanır.
export const questions: Question[] = [
  // ---------- Hukukun Temel Kavramları ----------
  {
    id: 1,
    konu: "Hukukun Temelleri",
    soru: "Hem yazılı hem yazısız hukuk kurallarını kapsayan hukuk türü hangisidir?",
    secenekler: ["Mevzu hukuk", "Pozitif hukuk", "Doğal hukuk", "Tabii hukuk"],
    dogru: 1,
  },
  {
    id: 2,
    konu: "Hukukun Temelleri",
    soru: "Sadece yazılı hukuk kurallarını ifade eden kavram hangisidir?",
    secenekler: ["Pozitif hukuk", "Doğal hukuk", "Mevzu hukuk", "Örf ve adet hukuku"],
    dogru: 2,
  },
  {
    id: 3,
    konu: "Hukukun Temelleri",
    soru: "'Olan değil, olması gereken hukuk' olarak tanımlanan hukuk türü nedir?",
    secenekler: ["Doğal (tabii) hukuk", "Pozitif hukuk", "Mevzu hukuk", "Yazılı hukuk"],
    dogru: 0,
  },
  {
    id: 4,
    konu: "Hukukun Temelleri",
    soru: "'Sözleşmede aksi kararlaştırılmadıkça' ifadesi hangi hukuk kuralı türüne işaret eder?",
    secenekler: ["Emredici hukuk", "Tamamlayıcı hukuk", "Tanımlayıcı hukuk", "Yasaklayıcı hukuk"],
    dogru: 1,
  },
  {
    id: 5,
    konu: "Adalet",
    soru: "Zenginden çok, fakirden az vergi alınması hangi adalet türüdür?",
    secenekler: ["Denkleştirici adalet", "Paylaştırıcı (dağıtıcı) adalet", "Sosyal adalet", "Mutlak adalet"],
    dogru: 1,
  },
  {
    id: 6,
    konu: "Adalet",
    soru: "Herkesten aynı miktarda vergi alınması hangi adalet türüdür?",
    secenekler: ["Paylaştırıcı adalet", "Sosyal adalet", "Denkleştirici adalet", "Doğal adalet"],
    dogru: 2,
  },
  {
    id: 7,
    konu: "Butlan",
    soru: "Sözleşmenin var olduğu ama sizin iptal ettirebileceğiniz butlan türü hangisidir?",
    secenekler: ["Mutlak butlan", "Nispi butlan", "Kesin hükümsüzlük", "Yokluk"],
    dogru: 1,
  },
  {
    id: 8,
    konu: "Yargı",
    soru: "İçtihadı birleştirme kararını hangi kurumlar verir?",
    secenekler: [
      "Anayasa Mahkemesi ve Danıştay",
      "Yargıtay ve Danıştay",
      "Yargıtay ve Anayasa Mahkemesi",
      "Sayıştay ve Danıştay",
    ],
    dogru: 1,
  },
  {
    id: 9,
    konu: "Hukukun Kaynakları",
    soru: "Aşağıdakilerden hangisi hukukun yardımcı kaynağıdır ve hâkim için bağlayıcı DEĞİLDİR?",
    secenekler: [
      "İçtihadı birleştirme kararları",
      "Bilimsel görüşler (doktrin)",
      "Kanunlar",
      "Cumhurbaşkanlığı kararnameleri",
    ],
    dogru: 1,
  },
  {
    id: 10,
    konu: "Hukukun Kaynakları",
    soru: "Hâkimin bakmak zorunda olduğu, bağlayıcı olan yardımcı kaynak hangisidir?",
    secenekler: ["Bilimsel görüşler", "İçtihadı birleştirme kararları", "Örf ve adet", "Basın açıklamaları"],
    dogru: 1,
  },
  {
    id: 11,
    konu: "Hukuk Boşluğu",
    soru: "Bir davada herhangi bir hükmün bulunmamasına ne denir?",
    secenekler: ["Kural içi boşluk", "Açık boşluk", "Örtülü boşluk", "Kanun boşluğu"],
    dogru: 1,
  },
  {
    id: 12,
    konu: "Hukuk Boşluğu",
    soru: "Ne yazılı ne yazısız hiçbir kaynakta hüküm bulunmamasına ne denir?",
    secenekler: ["Açık boşluk", "Hukuk boşluğu", "Kural içi boşluk", "Kanun boşluğu"],
    dogru: 1,
  },
  {
    id: 13,
    konu: "Hukuk Boşluğu",
    soru: "Kanunun bazı takdir yetkilerini hâkime bırakmasına ne denir?",
    secenekler: ["Açık boşluk", "Kural içi boşluk", "Hukuk boşluğu", "Kanun boşluğu"],
    dogru: 1,
  },
  {
    id: 14,
    konu: "Yorum Yöntemleri",
    soru: "Kuraldaki kelimelerin günlük ve hukuki anlamlarına, cümle yapısına bakılarak yapılan yorum hangisidir?",
    secenekler: ["Amaçsal (gai) yorum", "Lafzi (deyimsel) yorum", "Sistematik yorum", "Tarihi yorum"],
    dogru: 1,
  },
  {
    id: 15,
    konu: "Yorum Yöntemleri",
    soru: "Kuralın günümüzdeki amacına göre yapılan yorum hangisidir?",
    secenekler: ["Lafzi yorum", "Amaçsal (gai) yorum", "Deyimsel yorum", "Sistematik yorum"],
    dogru: 1,
  },
  {
    id: 16,
    konu: "Yorum Yöntemleri",
    soru: "Tüm yorum yöntemlerinin birleşiminden oluşan yorum türü hangisidir?",
    secenekler: ["Sistematik yorum", "Lafzi yorum", "Amaçsal yorum", "Tarihi yorum"],
    dogru: 0,
  },

  // ---------- Kişiler Hukuku ----------
  {
    id: 17,
    konu: "Kişiler Hukuku",
    soru: "Gaipliğe kim karar verir?",
    secenekler: ["Mülki amir", "Mahkeme", "Cumhurbaşkanı", "Nüfus müdürlüğü"],
    dogru: 1,
  },
  {
    id: 18,
    konu: "Kişiler Hukuku",
    soru: "Gaibin eşi ne şekilde evliliği sona erdirir?",
    secenekler: ["İdari kararla", "Mahkeme kararıyla boşanma", "Kendiliğinden", "Nüfus kaydıyla"],
    dogru: 1,
  },
  {
    id: 19,
    konu: "Kişiler Hukuku",
    soru: "Ölüm karinesine kim karar verir?",
    secenekler: ["Mahkeme", "Mülki amir", "Cumhurbaşkanı", "Savcı"],
    dogru: 1,
  },
  {
    id: 20,
    konu: "Ehliyet",
    soru: "Kişinin kendisi hak ve borç altına girebiliyorsa hangi ehliyete sahiptir?",
    secenekler: ["Hak ehliyeti", "Fiil ehliyeti", "Sınırlı ehliyet", "Dava ehliyeti"],
    dogru: 1,
  },
  {
    id: 21,
    konu: "Ehliyet",
    soru: "Bir kişiye yasal danışman atanmışsa ehliyet durumu nedir?",
    secenekler: ["Tam ehliyetli", "Sınırlı ehliyetli", "Sınırlı ehliyetsiz", "Tam ehliyetsiz"],
    dogru: 1,
  },
  {
    id: 22,
    konu: "Ehliyet",
    soru: "Ayırt etme gücü olan ancak kısıtlı olan kişi hangi ehliyet grubundadır?",
    secenekler: ["Sınırlı ehliyetli", "Sınırlı ehliyetsiz", "Tam ehliyetli", "Tam ehliyetsiz"],
    dogru: 1,
  },
  {
    id: 23,
    konu: "Ehliyet",
    soru: "Erginlikten küçük olanlar (16 yaşına döndürülerek tanımlanan kısıtlılar) hangi gruba girer?",
    secenekler: ["Sınırlı ehliyetli", "Tam ehliyetli", "Sınırlı ehliyetsiz", "Tam ehliyetsiz"],
    dogru: 2,
  },
  {
    id: 24,
    konu: "Tüzel Kişiler",
    soru: "Vakıf ne tür bir topluluktur?",
    secenekler: ["Kişi topluluğu", "Mal topluluğu", "Ortaklık", "Kamu kurumu"],
    dogru: 1,
  },
  {
    id: 25,
    konu: "Tüzel Kişiler",
    soru: "Kaç dernek bir araya gelerek federasyon kurar?",
    secenekler: ["3 dernek", "5 dernek", "7 dernek", "2 dernek"],
    dogru: 1,
  },
  {
    id: 26,
    konu: "Tüzel Kişiler",
    soru: "Kaç federasyon bir araya gelerek konfederasyon kurar?",
    secenekler: ["5 federasyon", "2 federasyon", "3 federasyon", "7 federasyon"],
    dogru: 2,
  },

  // ---------- Soybağı / Hısımlık / Miras ----------
  {
    id: 27,
    konu: "Aile Hukuku",
    soru: "Anne-baba ile çocuk arasındaki hukuki bağa ne denir?",
    secenekler: ["Hısımlık", "Soybağı", "Velayet", "Vesayet"],
    dogru: 1,
  },
  {
    id: 28,
    konu: "Hısımlık",
    soru: "Anne-baba ve büyükanne-büyükbaba hangi hısımlık türüne girer?",
    secenekler: ["Yan soy", "Üst-alt soy", "Kayın hısımlığı", "Evlilik hısımlığı"],
    dogru: 1,
  },
  {
    id: 29,
    konu: "Hısımlık",
    soru: "Kardeşler arasındaki hısımlık kaçıncı dereceden başlar?",
    secenekler: ["1. derece", "2. derece", "3. derece", "4. derece"],
    dogru: 1,
  },
  {
    id: 30,
    konu: "Hısımlık",
    soru: "Amca, teyze gibi hısımlar kaçıncı derecededir?",
    secenekler: ["2. derece", "3. derece", "4. derece", "1. derece"],
    dogru: 1,
  },
  {
    id: 31,
    konu: "Miras Hukuku",
    soru: "Vefat eden kişiye ne denir?",
    secenekler: ["Mirasçı", "Muris", "Tereke", "Vasi"],
    dogru: 1,
  },
  {
    id: 32,
    konu: "Miras Hukuku",
    soru: "Devredilebilir malların miras yoluyla geçen bütününe ne denir?",
    secenekler: ["Muris", "Tereke", "Vasiyet", "Nafaka"],
    dogru: 1,
  },
  {
    id: 33,
    konu: "Miras Hukuku",
    soru: "Tek taraflı olarak yapılan atama işlemine ne denir?",
    secenekler: ["Miras sözleşmesi", "Vasiyetname", "Tereke", "Muvazaa"],
    dogru: 1,
  },
  {
    id: 34,
    konu: "Miras Hukuku",
    soru: "İki taraflı olarak yapılan atama işlemine ne denir?",
    secenekler: ["Vasiyetname", "Miras sözleşmesi", "Tereke", "Defi"],
    dogru: 1,
  },

  // ---------- Ayni / Nispi Haklar ----------
  {
    id: 35,
    konu: "Eşya Hukuku",
    soru: "Eşya üzerinde herkese karşı ileri sürülebilen haklar hangisidir?",
    secenekler: ["Nispi hak", "Ayni hak", "Alacak hakkı", "Kişilik hakkı"],
    dogru: 1,
  },
  {
    id: 36,
    konu: "Eşya Hukuku",
    soru: "Eşya üzerinde tam yetki (kullanma, yararlanma, tasarruf) veren ayni hak hangisidir?",
    secenekler: ["İntifa hakkı", "Mülkiyet", "Rehin", "İrtifak"],
    dogru: 1,
  },
  {
    id: 37,
    konu: "Eşya Hukuku",
    soru: "Kullanma, yararlanma ve tasarruf yetkilerinin tamamını vermeyen ayni hak nedir?",
    secenekler: ["Mülkiyet", "Sınırlı ayni hak", "Tam ayni hak", "Zilyetlik"],
    dogru: 1,
  },
  {
    id: 38,
    konu: "Borçlar Hukuku",
    soru: "Sadece belirli kişilere karşı ileri sürülebilen hak türü hangisidir? (En güzel örneği alacak hakkı)",
    secenekler: ["Ayni hak", "Nispi (ilişkili) hak", "Mülkiyet", "İrtifak hakkı"],
    dogru: 1,
  },
  {
    id: 39,
    konu: "Borçlar Hukuku",
    soru: "Aşağıdakilerden hangileri devredilemez haklardandır?",
    secenekler: [
      "Mülkiyet ve rehin",
      "Nafaka, intifa ve oturma hakkı",
      "Alacak hakkı",
      "Tapu ve tescil",
    ],
    dogru: 1,
  },

  // ---------- Hukuki Fiil / İşlem ----------
  {
    id: 40,
    konu: "Hukuki İşlemler",
    soru: "Hukukun sonuç bağladığı insan davranışlarına ne denir?",
    secenekler: ["Hukuki olay", "Hukuki fiil", "Hukuki işlem", "Edim"],
    dogru: 1,
  },
  {
    id: 41,
    konu: "Hukuki İşlemler",
    soru: "Hukukun sonuç bağladığı doğa olaylarına ne denir?",
    secenekler: ["Hukuki fiil", "Hukuki olay", "Hukuki işlem", "İfa"],
    dogru: 1,
  },
  {
    id: 42,
    konu: "Hukuki İşlemler",
    soru: "Bir kişinin satması, diğerinin alması gibi iradeye dayalı işleme ne denir?",
    secenekler: ["Hukuki olay", "Hukuki işlem", "Hukuki fiil", "Temerrüt"],
    dogru: 1,
  },
  {
    id: 43,
    konu: "Borçlar Hukuku",
    soru: "Borcun zamanında yerine getirilememesine ne denir?",
    secenekler: ["İfa", "Temerrüt", "Edim", "Defi"],
    dogru: 1,
  },
  {
    id: 44,
    konu: "Aile Hukuku",
    soru: "Ana-babanın çocuk üzerindeki hak ve yetkilerine ne denir?",
    secenekler: ["Vesayet", "Velayet", "Kayyımlık", "Soybağı"],
    dogru: 1,
  },
  {
    id: 45,
    konu: "Borçlar Hukuku",
    soru: "Borçlunun alacaklı karşısında yerine getirmesi gerekene ne denir?",
    secenekler: ["İfa", "Edim", "Temerrüt", "Defi"],
    dogru: 1,
  },
  {
    id: 46,
    konu: "Borçlar Hukuku",
    soru: "Borcun yerine getirilmesine ne denir?",
    secenekler: ["Edim", "İfa", "Temerrüt", "Defi"],
    dogru: 1,
  },
  {
    id: 47,
    konu: "Borçlar Hukuku",
    soru: "Borçlunun haklı bir sebep öne sürerek ödemekten kaçınmasına ne denir?",
    secenekler: ["İtiraz", "Defi", "Temerrüt", "İfa"],
    dogru: 1,
  },

  // ---------- Dava Türleri ----------
  {
    id: 48,
    konu: "Dava Türleri",
    soru: "Bir şeyin var olup olmadığını belirlemek için açılan dava hangisidir?",
    secenekler: ["Eda davası", "Tespit davası", "İnşai dava", "Tam yargı davası"],
    dogru: 1,
  },
  {
    id: 49,
    konu: "Dava Türleri",
    soru: "Yeni bir hukuki durum doğuran (yenilik doğuran) dava hangisidir?",
    secenekler: ["Tespit davası", "İnşai dava", "Eda davası", "İtiraz davası"],
    dogru: 1,
  },
  {
    id: 50,
    konu: "Ceza/Hukuk Kavramları",
    soru: "Birinin malına, başka birini korumak amacıyla zarar verilmesine ne denir?",
    secenekler: ["Meşru müdafaa", "Iztırar (zaruret) hali", "Zorunluluk", "Haklı sebep"],
    dogru: 1,
  },
  {
    id: 51,
    konu: "Hukuk Kavramları",
    soru: "Borcun mahkeme aracılığıyla yeniden yapılandırılmasına ne denir?",
    secenekler: ["İcra", "Konkordato", "Haciz", "İflas"],
    dogru: 1,
  },
  {
    id: 52,
    konu: "Hukuk Kavramları",
    soru: "Gerçekte bağış olan bir işlemi yalandan satış gibi gösterme durumuna ne denir?",
    secenekler: ["Defi", "Muvazaa", "Temerrüt", "İfa"],
    dogru: 1,
  },
  {
    id: 53,
    konu: "Ceza Hukuku",
    soru: "Ceza davasında mağduru savunan avukata ne denir?",
    secenekler: ["Müdafi", "Vekil", "Hâkim", "Savcı"],
    dogru: 1,
  },
  {
    id: 54,
    konu: "Ceza Hukuku",
    soru: "Ceza davasında sanığı (suçluyu) savunan avukata ne denir?",
    secenekler: ["Vekil", "Müdafi", "Bilirkişi", "Hakem"],
    dogru: 1,
  },
  {
    id: 55,
    konu: "Ceza Hukuku",
    soru: "Gözaltı süresi tek kişide en fazla ne kadardır?",
    secenekler: ["24 saat", "48 saat", "72 saat", "4 gün"],
    dogru: 1,
  },
  {
    id: 56,
    konu: "Ceza Hukuku",
    soru: "Toplu suçlarda gözaltı süresi en fazla ne kadardır?",
    secenekler: ["48 saat", "3 gün", "4 gün", "7 gün"],
    dogru: 2,
  },

  // ---------- Anayasa Tarihi ----------
  {
    id: 57,
    konu: "Anayasa Tarihi",
    soru: "1982 Anayasası'nı hazırlayan konsey hangisidir?",
    secenekler: [
      "Milli Birlik Komitesi",
      "Milli Güvenlik ve Danışma Konseyi",
      "Kurucu Meclis",
      "Temsilciler Meclisi",
    ],
    dogru: 1,
  },
  {
    id: 58,
    konu: "Anayasa Tarihi",
    soru: "Millet Meclisi ve Cumhuriyet Senatosu hangi anayasa döneminde vardı?",
    secenekler: ["1924", "1961", "1982", "1921"],
    dogru: 1,
  },
  {
    id: 59,
    konu: "Anayasa Tarihi",
    soru: "Türkiye'de kaç kez referandum (halk oylaması) yapılmıştır (nota göre)?",
    secenekler: ["5 kez", "6 kez", "7 kez", "8 kez"],
    dogru: 2,
  },
  {
    id: 60,
    konu: "Anayasa Tarihi",
    soru: "Laiklik ilkesi anayasaya hangi yılda girmiştir?",
    secenekler: ["1928", "1937", "1924", "1946"],
    dogru: 1,
  },
  {
    id: 61,
    konu: "Anayasa Tarihi",
    soru: "Tek dereceli seçimler ilk hangi yılda yapılmıştır?",
    secenekler: ["1934", "1946", "1950", "1961"],
    dogru: 1,
  },
  {
    id: 62,
    konu: "Anayasa Tarihi",
    soru: "YÖK hangi anayasa ile kurulmuştur?",
    secenekler: ["1961", "1982", "1971", "2010"],
    dogru: 1,
  },
  {
    id: 63,
    konu: "Kurumların Kuruluşu",
    soru: "Kamu Denetçiliği Kurumu (Ombudsman) hangi yılda kurulmuştur?",
    secenekler: ["1982", "2010", "1961", "2017"],
    dogru: 1,
  },
  {
    id: 64,
    konu: "Kurumların Kuruluşu",
    soru: "Kamu Hakem Kurulu (Yüksek Hakem Kurulu) hangi anayasa ile düzenlenmiştir?",
    secenekler: ["1961", "2010", "1982", "1924"],
    dogru: 2,
  },
  {
    id: 65,
    konu: "Kurumların Kuruluşu",
    soru: "Atatürk Kültür, Dil ve Tarih Yüksek Kurumu hangi anayasa ile kurulmuştur?",
    secenekler: ["1961", "1982", "2010", "1924"],
    dogru: 1,
  },
  {
    id: 66,
    konu: "Kurumların Kuruluşu",
    soru: "Devlet Planlama Teşkilatı hangi anayasa döneminde kurulmuştur?",
    secenekler: ["1982", "1961", "2010", "1924"],
    dogru: 1,
  },
  {
    id: 67,
    konu: "Anayasa Özellikleri",
    soru: "Madde kenar başlıkları 1982 Anayasası'nda metne dahil midir?",
    secenekler: ["Evet, dahildir", "Hayır, dahil değildir", "Sadece bazıları dahildir", "Belirtilmemiştir"],
    dogru: 1,
  },
  {
    id: 68,
    konu: "Anayasa Özellikleri",
    soru: "'İnsan haklarına saygılı devlet' ifadesi hangi anayasada yer alır?",
    secenekler: ["1961", "1982", "1924", "1921"],
    dogru: 1,
  },
  {
    id: 69,
    konu: "Anayasa Özellikleri",
    soru: "'İnsan haklarına dayalı devlet' ifadesi hangi anayasada yer alır?",
    secenekler: ["1982", "1961", "1924", "2010"],
    dogru: 1,
  },

  // ---------- Egemenlik / Haklar ----------
  {
    id: 70,
    konu: "Egemenlik",
    soru: "Anayasaya göre yasama ve yargı yetkisi kimin adına kullanılır?",
    secenekler: ["Cumhurbaşkanı", "Türk Milleti", "TBMM", "Devlet"],
    dogru: 1,
  },
  {
    id: 71,
    konu: "Egemenlik",
    soru: "Yürütme yetkisi kimin adına kullanılır?",
    secenekler: ["Türk Milleti", "Cumhurbaşkanı", "TBMM", "Bakanlar Kurulu"],
    dogru: 1,
  },
  {
    id: 72,
    konu: "Temel Haklar",
    soru: "Dokunulmaz, devredilmez ve hiçbir şekilde sınırlandırılamayan haklara ne denir?",
    secenekler: ["Sosyal haklar", "Sert çekirdek haklar", "Siyasi haklar", "Negatif haklar"],
    dogru: 1,
  },
  {
    id: 73,
    konu: "Temel Haklar",
    soru: "Yabancıların temel haklarının sınırlanmasında kanun dışında neye de uygunluk aranır?",
    secenekler: [
      "Cumhurbaşkanı kararnamesine",
      "Milletlerarası hukuka",
      "Yönetmeliğe",
      "İç tüzüğe",
    ],
    dogru: 1,
  },
  {
    id: 74,
    konu: "Temel Haklar",
    soru: "Devletin bize yardım ettiği haklar (eğitim, sağlık gibi) hangi gruptadır?",
    secenekler: ["Negatif haklar", "Sosyal ve ekonomik haklar", "Siyasi haklar", "Kişi hakları"],
    dogru: 1,
  },
  {
    id: 75,
    konu: "Temel Haklar",
    soru: "Bizi devlete karşı koruyan haklara ne denir?",
    secenekler: ["Pozitif haklar", "Negatif haklar", "Siyasi haklar", "Sosyal haklar"],
    dogru: 1,
  },
  {
    id: 76,
    konu: "Temel Haklar",
    soru: "Yönetime katılabildiğimiz haklara ne denir?",
    secenekler: ["Negatif haklar", "Siyasi haklar", "Sosyal haklar", "Ekonomik haklar"],
    dogru: 1,
  },

  // ---------- Yerleşme / Seyahat ----------
  {
    id: 77,
    konu: "Kişi Hakları",
    soru: "Yerleşme hürriyeti hangi sebeplerle sınırlandırılamaz?",
    secenekler: [
      "Suç işlemeyi önlemek",
      "Sağlıklı ve düzenli kentleşmeyi gerçekleştirmek",
      "Vatandaşlıktan çıkarmak",
      "Sosyal ve ekonomik gelişmeyi sağlamak",
    ],
    dogru: 2,
  },
  {
    id: 78,
    konu: "Kişi Hakları",
    soru: "Seyahat hürriyetinin sınırlandırılma sebeplerinden biri hangisidir?",
    secenekler: [
      "Vergi toplamak",
      "Suç soruşturma ve kovuşturması sebebiyle",
      "Kentleşmeyi düzenlemek",
      "Sosyal gelişme sağlamak",
    ],
    dogru: 1,
  },
  {
    id: 79,
    konu: "Kişi Hakları",
    soru: "Vatandaşın yurt dışına çıkışını kim engelleyebilir?",
    secenekler: ["Vali", "Hâkim (sadece)", "Cumhurbaşkanı", "Mülki amir"],
    dogru: 1,
  },
  {
    id: 80,
    konu: "Kişi Hakları",
    soru: "Özel hayatın gizliliği ile ilgili düzenleme anayasaya hangi yılda girmiştir?",
    secenekler: ["1982", "2010", "2017", "1961"],
    dogru: 1,
  },

  // ---------- Sınırlama Sebepleri ----------
  {
    id: 81,
    konu: "Hakların Sınırlanması",
    soru: "Aşağıdakilerden hangisi özel hayatın gizliliği, haberleşme, konut dokunulmazlığı gibi hakların sınırlanma sebeplerinden biridir?",
    secenekler: ["Kamu yararı", "Milli güvenlik", "Ekonomik gelişme", "Kentleşme"],
    dogru: 1,
  },
  {
    id: 82,
    konu: "Hakların Sınırlanması",
    soru: "'Kamu yararı' sınırlama sebebi genellikle hangi hakka özgüdür?",
    secenekler: ["Haberleşme hürriyeti", "Mülkiyet hakkı", "Konut dokunulmazlığı", "Dernek kurma"],
    dogru: 1,
  },

  // ---------- Güvenceler / Md 38 ----------
  {
    id: 83,
    konu: "Anayasal Güvenceler",
    soru: "'Hiç kimse kanunen tabi olduğu mahkemeden başka mahkemeye çıkarılamaz' ilkesi hangisidir?",
    secenekler: ["Masumiyet karinesi", "Kanuni hâkim güvencesi", "Adil yargılanma", "Hukuk devleti"],
    dogru: 1,
  },
  {
    id: 84,
    konu: "Anayasal Güvenceler",
    soru: "Anayasanın 38. maddesi neyle ilgili esasları düzenler?",
    secenekler: [
      "Seçme ve seçilme hakkı",
      "Suç ve cezalara ilişkin esaslar",
      "Mülkiyet hakkı",
      "Yerleşme hürriyeti",
    ],
    dogru: 1,
  },

  // ---------- Hakem / Toplu Sözleşme ----------
  {
    id: 85,
    konu: "İş/Hakem Kurumları",
    soru: "Aşağıdaki kurumlardan hangisinin kararları kesindir, üst mercie götürülemez?",
    secenekler: [
      "İdare Mahkemesi",
      "Yüksek Hakem Kurulu / Spor Tahkim Kurumu",
      "Danıştay",
      "Yargıtay",
    ],
    dogru: 1,
  },
  {
    id: 86,
    konu: "İş/Hakem Kurumları",
    soru: "Kamu görevlileri (memurlar) toplu sözleşmede anlaşamazlarsa nereye giderler?",
    secenekler: ["Yüksek Hakem Kurulu", "Kamu Görevlileri Hakem Kurulu", "Danıştay", "Yargıtay"],
    dogru: 1,
  },
  {
    id: 87,
    konu: "İş/Hakem Kurumları",
    soru: "İşçiler toplu iş sözleşmesinde anlaşamazlarsa nereye gidilir?",
    secenekler: ["Kamu Görevlileri Hakem Kurulu", "Yüksek Hakem Kurulu", "İş Mahkemesi", "Danıştay"],
    dogru: 1,
  },
  {
    id: 88,
    konu: "İş Hukuku",
    soru: "Grev hakkı kimlere aittir?",
    secenekler: ["Memurlara", "İşçilere", "Herkese", "Kamu görevlilerine"],
    dogru: 1,
  },

  // ---------- İzin Aranmayanlar ----------
  {
    id: 89,
    konu: "Hürriyetler",
    soru: "Aşağıdakilerden hangisi için kural olarak izin aranmaz?",
    secenekler: [
      "Radyo yayını",
      "Dernek, toplantı-gösteri, sendika kurma",
      "TV yayını",
      "Silah taşıma",
    ],
    dogru: 1,
  },
  {
    id: 90,
    konu: "Hürriyetler",
    soru: "Aşağıdakilerden hangisi için gerektiğinde izin alınabilir?",
    secenekler: [
      "Dernek kurma",
      "Radyo ve televizyon yayınları",
      "Süreli yayın çıkarma",
      "Siyasi parti kurma",
    ],
    dogru: 1,
  },

  // ---------- Sosyal Devlet / Çalışanlar ----------
  {
    id: 91,
    konu: "Sosyal Devlet",
    soru: "Anayasaya göre 'Türk toplumunun temeli' nedir?",
    secenekler: ["Devlet", "Aile", "Millet", "Vatan"],
    dogru: 1,
  },
  {
    id: 92,
    konu: "Sosyal Devlet",
    soru: "Aşağıdakilerden hangisi çalışma hayatında özel olarak korunanlardan DEĞİLDİR?",
    secenekler: ["Küçükler", "Kadınlar", "Bedeni ve ruhi yetersiz olanlar", "Emekliler"],
    dogru: 3,
  },

  // ---------- Oy Kullanma ----------
  {
    id: 93,
    konu: "Seçme Hakkı",
    soru: "Oy kullanabilmek için gereken yaş kaçtır?",
    secenekler: ["17", "18", "20", "21"],
    dogru: 1,
  },
  {
    id: 94,
    konu: "Seçme Hakkı",
    soru: "Aşağıdakilerden hangisi oy kullanabilir?",
    secenekler: [
      "Askeri öğrenciler",
      "Silah altındaki er ve erbaşlar",
      "Taksirli suçtan hükümlüler",
      "Kasıtlı suçtan hükümlüler",
    ],
    dogru: 2,
  },
  {
    id: 95,
    konu: "Seçme Hakkı",
    soru: "Aşağıdakilerden hangisi oy kullanamaz?",
    secenekler: [
      "Tutuklular",
      "Taksirli suç hükümlüleri",
      "Kasıtlı suçtan hükümlüler",
      "18 yaşını dolduranlar",
    ],
    dogru: 2,
  },
  {
    id: 96,
    konu: "Seçim Tarihi",
    soru: "Gizli oy ilkesi hangi yılda gelmiştir?",
    secenekler: ["1934", "1946", "1950", "1961"],
    dogru: 2,
  },
  {
    id: 97,
    konu: "Seçim Tarihi",
    soru: "Genel oy ilkesi hangi yılda gelmiştir?",
    secenekler: ["1934", "1946", "1950", "1924"],
    dogru: 0,
  },
  {
    id: 98,
    konu: "Seçim Tarihi",
    soru: "Tek dereceli seçim hangi yıldan itibaren uygulanmaya başlamıştır?",
    secenekler: ["1934", "1946", "1950", "1961"],
    dogru: 1,
  },

  // ---------- Siyasi Partiler ----------
  {
    id: 99,
    konu: "Siyasi Partiler",
    soru: "Siyasi partilerin kapatılması davasını kim açar?",
    secenekler: [
      "Adalet Bakanı",
      "Yargıtay Cumhuriyet Başsavcısı",
      "Cumhurbaşkanı",
      "Danıştay Başkanı",
    ],
    dogru: 1,
  },
  {
    id: 100,
    konu: "Siyasi Partiler",
    soru: "Partinin kapatılmasına yol açan üyeler kaç yıl parti üyesi olamaz?",
    secenekler: ["3 yıl", "5 yıl", "7 yıl", "10 yıl"],
    dogru: 1,
  },
  {
    id: 101,
    konu: "Seçim",
    soru: "Seçim kanunlarındaki değişiklikler kaç süre içindeki seçimlerde uygulanamaz?",
    secenekler: ["6 ay", "1 yıl", "2 yıl", "3 ay"],
    dogru: 1,
  },
  {
    id: 102,
    konu: "Vatandaşlık",
    soru: "Kişinin kendi isteğiyle vatandaşlıktan çıkarılmasına kim karar verir?",
    secenekler: ["TBMM", "Cumhurbaşkanı", "İçişleri Bakanı", "Danıştay"],
    dogru: 1,
  },
  {
    id: 103,
    konu: "Vatandaşlık",
    soru: "Vatandaşlıktan çıkarma işlemine itiraz davası nerede açılır?",
    secenekler: ["Yargıtay", "Danıştay", "Anayasa Mahkemesi", "İdare Mahkemesi"],
    dogru: 1,
  },

  // ---------- Sendika / Dernek ----------
  {
    id: 104,
    konu: "Örgütlenme",
    soru: "Sendikaları kimler kurabilir?",
    secenekler: ["Sadece işçiler", "Çalışanlar ve işverenler", "Herkes", "Sadece memurlar"],
    dogru: 1,
  },
  {
    id: 105,
    konu: "Örgütlenme",
    soru: "Derneği kimler kurabilir?",
    secenekler: ["Sadece işçiler", "Herkes", "Sadece memurlar", "Çalışanlar ve işverenler"],
    dogru: 1,
  },

  // ---------- Ombudsman ----------
  {
    id: 106,
    konu: "Kamu Denetçiliği",
    soru: "Kamu Denetçiliği Kurumu hangi makama bağlıdır?",
    secenekler: ["Cumhurbaşkanlığı", "TBMM (Meclis Başkanlığı)", "Adalet Bakanlığı", "Danıştay"],
    dogru: 1,
  },
  {
    id: 107,
    konu: "Kamu Denetçiliği",
    soru: "Kamu Denetçiliği Kurumu'nun (Ombudsman) kararları için hangisi doğrudur?",
    secenekler: ["Bağlayıcıdır", "Tavsiye niteliğindedir", "Kesindir", "Kanun hükmündedir"],
    dogru: 1,
  },

  // ---------- Yasama ----------
  {
    id: 108,
    konu: "Yasama",
    soru: "Yasama organının her ayrıntıyı düzenleyebilmesine ne denir?",
    secenekler: ["Yasama asliliği", "Yasama genelliği", "Yasama sürekliliği", "Yasama bağımsızlığı"],
    dogru: 1,
  },
  {
    id: 109,
    konu: "Yasama",
    soru: "Yasamanın bir konuda işlem yaparken başka bir kural ile bağlı olmamasına ne denir?",
    secenekler: ["Yasama genelliği", "Yasama asliliği", "Yasama dokunulmazlığı", "Yasama sorumsuzluğu"],
    dogru: 1,
  },
  {
    id: 110,
    konu: "Seçimlerin Yenilenmesi",
    soru: "Seçimlerin yenilenmesine kimler karar verebilir?",
    secenekler: [
      "Sadece Cumhurbaşkanı",
      "360 milletvekili ya da Cumhurbaşkanı",
      "301 milletvekili",
      "TBMM Başkanı",
    ],
    dogru: 1,
  },
  {
    id: 111,
    konu: "Seçimlerin Ertelenmesi",
    soru: "Savaş sebebiyle seçimlerin geriye bırakılmasına kim karar verir?",
    secenekler: ["Cumhurbaşkanı", "TBMM", "YSK", "Anayasa Mahkemesi"],
    dogru: 1,
  },
  {
    id: 112,
    konu: "Ara Seçim",
    soru: "Ara seçim ile ilgili aşağıdakilerden hangisi doğrudur?",
    secenekler: [
      "Bir dönemde 2 kez yapılır",
      "Bir dönemde 1 kez yapılır",
      "Her yıl yapılır",
      "Hiç yapılmaz",
    ],
    dogru: 1,
  },
  {
    id: 113,
    konu: "Ara Seçim",
    soru: "Ara seçime genel seçimden en erken kaç ay sonra gidilir?",
    secenekler: ["12 ay", "24 ay", "30 ay", "36 ay"],
    dogru: 2,
  },
  {
    id: 114,
    konu: "Ara Seçim",
    soru: "Genel seçime kaç süre kala ara seçime gidilmez?",
    secenekler: ["6 ay", "1 yıl", "2 yıl", "3 ay"],
    dogru: 1,
  },
  {
    id: 115,
    konu: "Ara Seçim",
    soru: "Mecliste boşalma yüzde kaça ulaşırsa 3 ay içinde ara seçime gidilir?",
    secenekler: ["%3", "%5", "%10", "%7"],
    dogru: 1,
  },
  {
    id: 116,
    konu: "YSK",
    soru: "Yüksek Seçim Kurulu kaç asıl kaç yedek üyeden oluşur?",
    secenekler: ["7 asıl 4 yedek", "6 asıl 3 yedek", "11 asıl 4 yedek", "5 asıl 2 yedek"],
    dogru: 0,
  },
  {
    id: 117,
    konu: "YSK",
    soru: "YSK üyelerini hangi kurumlar seçer?",
    secenekler: [
      "TBMM ve Cumhurbaşkanı",
      "6'sı Yargıtay, 5'i Danıştay",
      "Hepsi Yargıtay",
      "Hepsi Danıştay",
    ],
    dogru: 1,
  },
  {
    id: 118,
    konu: "YSK",
    soru: "YSK hangi yılda kurulmuştur (beyaz devrim)?",
    secenekler: ["1946", "1950", "1961", "1934"],
    dogru: 1,
  },
  {
    id: 119,
    konu: "YSK",
    soru: "YSK hangi anayasa ile anayasal kurum haline gelmiştir?",
    secenekler: ["1961", "1982", "1924", "2010"],
    dogru: 0,
  },

  // ---------- Milletvekilliği ----------
  {
    id: 120,
    konu: "Milletvekilliği",
    soru: "Milletvekili seçilen kişi sıfatını ne zaman kazanır?",
    secenekler: [
      "Ant içtiğinde",
      "Mazbatayı teslim aldığında",
      "Seçim sonuçları açıklandığında",
      "Görev başladığında",
    ],
    dogru: 1,
  },
  {
    id: 121,
    konu: "Milletvekilliği",
    soru: "Milletvekili göreve ne zaman başlar?",
    secenekler: ["Mazbatayı aldığında", "Ant içtiğinde", "Seçildiğinde", "İlk oturumda"],
    dogru: 1,
  },
  {
    id: 122,
    konu: "Meclis Grubu",
    soru: "Bir siyasi partinin meclis grubu kurabilmesi için en az kaç milletvekili gerekir?",
    secenekler: ["5", "10", "20", "3"],
    dogru: 1,
  },
  {
    id: 123,
    konu: "Milletvekilliği",
    soru: "Milletvekili seçilmeye engel olan durum aşağıdakilerden hangisidir?",
    secenekler: [
      "Taksirli suçtan hüküm",
      "Kasıtlı suçtan 1 yıl üzeri ceza",
      "18 yaşını doldurmak",
      "Askerlik yapmak",
    ],
    dogru: 1,
  },

  // ---------- RTÜK / Sayıştay ----------
  {
    id: 124,
    konu: "Bağımsız Kurumlar",
    soru: "RTÜK kaç üyeden oluşur ve üyeleri kim seçer?",
    secenekler: [
      "7 üye, Cumhurbaşkanı",
      "9 üye, TBMM",
      "11 üye, TBMM",
      "5 üye, Cumhurbaşkanı",
    ],
    dogru: 1,
  },
  {
    id: 125,
    konu: "Bağımsız Kurumlar",
    soru: "Sayıştay üyeleri kim tarafından seçilir?",
    secenekler: ["Cumhurbaşkanı", "TBMM", "Danıştay", "Yargıtay"],
    dogru: 1,
  },

  // ---------- Anayasa Değişikliği ----------
  {
    id: 126,
    konu: "Anayasa Değişikliği",
    soru: "Anayasa değişikliği teklifi için en az kaç milletvekili gerekir?",
    secenekler: ["184", "200", "360", "301"],
    dogru: 1,
  },
  {
    id: 127,
    konu: "Anayasa Değişikliği",
    soru: "Anayasa değişikliği teklifi Genel Kurul'da kaç kez görüşülür?",
    secenekler: ["1 kez", "2 kez", "3 kez", "4 kez"],
    dogru: 1,
  },
  {
    id: 128,
    konu: "Anayasa Değişikliği",
    soru: "Anayasa değişikliğinin kabulü için en az kaç oy gerekir?",
    secenekler: ["301", "360", "400", "184"],
    dogru: 1,
  },
  {
    id: 129,
    konu: "Anayasa Değişikliği",
    soru: "Anayasa değişikliği kaç oyun üzerinde olursa referanduma gerek kalmaz?",
    secenekler: ["360", "400", "301", "450"],
    dogru: 1,
  },
  {
    id: 130,
    konu: "Anayasa Değişikliği",
    soru: "Anayasa değişikliği 360-400 arası oy alırsa ne olur?",
    secenekler: [
      "Doğrudan yürürlüğe girer",
      "Referanduma sunulur",
      "Reddedilir",
      "Cumhurbaşkanı onaylar",
    ],
    dogru: 1,
  },

  // ---------- TSK / Kanun Yayımlama ----------
  {
    id: 131,
    konu: "Yürütme",
    soru: "Türk Silahlı Kuvvetleri'nin başkomutanlığını kimler kullanır?",
    secenekler: [
      "Sadece Cumhurbaşkanı",
      "TBMM ve Cumhurbaşkanı",
      "Genelkurmay Başkanı",
      "Milli Savunma Bakanı",
    ],
    dogru: 1,
  },
  {
    id: 132,
    konu: "Yasama",
    soru: "Cumhurbaşkanı kanunları kaç gün içinde Resmi Gazete'de yayımlar?",
    secenekler: ["7 gün", "15 gün", "30 gün", "10 gün"],
    dogru: 1,
  },
  {
    id: 133,
    konu: "Bütçe",
    soru: "Bütçe kanununu kim teklif eder (verir)?",
    secenekler: ["TBMM", "Cumhurbaşkanı", "Maliye Bakanı", "Sayıştay"],
    dogru: 1,
  },
  {
    id: 134,
    konu: "İç Tüzük",
    soru: "İç tüzüğü kim yayımlar?",
    secenekler: ["Cumhurbaşkanı", "TBMM Meclis Başkanı", "Adalet Bakanı", "Danıştay"],
    dogru: 1,
  },

  // ---------- Meclis Tatili ----------
  {
    id: 135,
    konu: "Meclis Çalışması",
    soru: "Meclis en fazla kaç ay tatil yapabilir?",
    secenekler: ["1 ay", "3 ay", "6 ay", "2 ay"],
    dogru: 1,
  },
  {
    id: 136,
    konu: "Meclis Çalışması",
    soru: "Meclisin ara vermesi (ara tatil) en fazla kaç gündür?",
    secenekler: ["7 gün", "15 gün", "30 gün", "10 gün"],
    dogru: 1,
  },
  {
    id: 137,
    konu: "Meclis Çalışması",
    soru: "Meclisi olağanüstü toplantıya kaç milletvekili dolaylı olarak (Meclis Başkanına başvurarak) çağırabilir?",
    secenekler: ["100", "110", "120", "184"],
    dogru: 2,
  },

  // ---------- Nitelikli Oylar ----------
  {
    id: 138,
    konu: "Nitelikli Oylar",
    soru: "Genel af çıkarılabilmesi için kaç oy gerekir?",
    secenekler: ["301", "360", "400", "184"],
    dogru: 1,
  },
  {
    id: 139,
    konu: "Nitelikli Oylar",
    soru: "Devamsızlık nedeniyle üyeliğin düşmesi için gerekli oy sayısı kaçtır?",
    secenekler: ["301", "360", "400", "184"],
    dogru: 0,
  },
  {
    id: 140,
    konu: "Nitelikli Oylar",
    soru: "Cumhurbaşkanı hakkında soruşturma açılmasını istemek için kaç oy gerekir?",
    secenekler: ["301", "360", "400", "184"],
    dogru: 0,
  },
  {
    id: 141,
    konu: "Meclis Devamsızlığı",
    soru: "Bir ay içinde kaç birleşime katılmayan milletvekilinin üyeliği düşürülebilir?",
    secenekler: ["3", "5", "7", "10"],
    dogru: 1,
  },
  {
    id: 142,
    konu: "Yasama",
    soru: "Cumhurbaşkanının geri gönderdiği bir yasayı Meclisin aynen kabul edebilmesi için kaç oy gerekir?",
    secenekler: ["184", "301", "360", "400"],
    dogru: 1,
  },

  // ---------- Denetim Yolları ----------
  {
    id: 143,
    konu: "Meclis Denetimi",
    soru: "Cumhurbaşkanı yardımcıları ve bakanlara yazılı soru sorulduğunda cevap en geç kaç günde verilir?",
    secenekler: ["7 gün", "15 gün", "30 gün", "10 gün"],
    dogru: 1,
  },
  {
    id: 144,
    konu: "Meclis Denetimi",
    soru: "Devleti ve toplumu ilgilendiren konuların görüşüldüğü denetim yolu hangisidir?",
    secenekler: ["Meclis soruşturması", "Genel görüşme", "Yazılı soru", "Gensoru"],
    dogru: 1,
  },
  {
    id: 145,
    konu: "Meclis Soruşturması",
    soru: "Meclis soruşturması açılmasını istemek için kaç milletvekili gerekir?",
    secenekler: ["301", "360", "400", "184"],
    dogru: 0,
  },
  {
    id: 146,
    konu: "Meclis Soruşturması",
    soru: "Meclis soruşturmasının açılmasına kaç oyla karar verilir?",
    secenekler: ["301", "360", "400", "184"],
    dogru: 1,
  },
  {
    id: 147,
    konu: "Meclis Soruşturması",
    soru: "Yüce Divan'a sevk için kaç oy gerekir?",
    secenekler: ["301", "360", "400", "450"],
    dogru: 2,
  },
  {
    id: 148,
    konu: "Yüce Divan",
    soru: "Yüce Divan görevi ne kadar sürer (uzatma dahil)?",
    secenekler: ["1 ay + 1 ay", "3 ay + 3 ay", "6 ay + 6 ay", "2 ay + 2 ay"],
    dogru: 1,
  },

  // ---------- Meclis Başkanı ----------
  {
    id: 149,
    konu: "Meclis Başkanı",
    soru: "Meclis Başkanı seçimi kaç tur olabilir?",
    secenekler: ["2 tur", "3 tur", "4 tur", "5 tur"],
    dogru: 2,
  },
  {
    id: 150,
    konu: "Meclis Başkanı",
    soru: "Meclis Başkanı 4. turda nasıl seçilir?",
    secenekler: ["400 oyla", "361 oyla", "En çok oyu alan", "Salt çoğunlukla"],
    dogru: 2,
  },
  {
    id: 151,
    konu: "Meclis Güvenliği",
    soru: "Meclisin güvenliğinden kim sorumludur?",
    secenekler: ["İçişleri Bakanlığı", "TBMM Başkanlığı", "Cumhurbaşkanlığı", "Genelkurmay"],
    dogru: 1,
  },
  {
    id: 152,
    konu: "Yasama",
    soru: "Dönem sonunda sonuçlanmayan kanun teklifi ne olur?",
    secenekler: ["Devam eder", "Kadük (hükümsüz) olur", "Referanduma sunulur", "Otomatik kabul edilir"],
    dogru: 1,
  },
  {
    id: 153,
    konu: "Milletvekilliği",
    soru: "Milletvekilleri en fazla kaç aylık avans alabilirler?",
    secenekler: ["1 aylık", "2 aylık", "3 aylık", "6 aylık"],
    dogru: 2,
  },

  // ---------- Cumhurbaşkanı ----------
  {
    id: 154,
    konu: "Cumhurbaşkanı Seçimi",
    soru: "Cumhurbaşkanı adayı gösterebilmek için partilerin son genel seçimde aldığı oy oranı en az kaç olmalıdır?",
    secenekler: ["%3", "%5", "%7", "%10"],
    dogru: 1,
  },
  {
    id: 155,
    konu: "Cumhurbaşkanı",
    soru: "Cumhurbaşkanlığı makamı boşalırsa kaç gün içinde seçim yapılır?",
    secenekler: ["30 gün", "45 gün", "60 gün", "90 gün"],
    dogru: 1,
  },
  {
    id: 156,
    konu: "Cumhurbaşkanı",
    soru: "Cumhurbaşkanlığı boşaldığında yerine kim vekalet eder?",
    secenekler: ["Meclis Başkanı", "Cumhurbaşkanı yardımcısı", "En yaşlı bakan", "Başbakan"],
    dogru: 1,
  },
  {
    id: 157,
    konu: "Cumhurbaşkanı",
    soru: "Cumhurbaşkanlığı boşaldığında genel seçime 1 yıldan az kalmışsa ne yapılır?",
    secenekler: [
      "Sadece Cumhurbaşkanı seçimi yapılır",
      "Cumhurbaşkanı ve Meclis seçimi birlikte yapılır",
      "Hiçbir seçim yapılmaz",
      "Referandum yapılır",
    ],
    dogru: 1,
  },
  {
    id: 158,
    konu: "Cumhurbaşkanı",
    soru: "Cumhurbaşkanlığı boşaldığında genel seçime 1 yıldan fazla kalmışsa ne yapılır?",
    secenekler: [
      "Sadece Cumhurbaşkanı seçimi yapılır",
      "Cumhurbaşkanı ve Meclis birlikte seçilir",
      "Referandum yapılır",
      "Meclis feshedilir",
    ],
    dogru: 0,
  },

  // ---------- Kararnameler ----------
  {
    id: 159,
    konu: "Kararnameler",
    soru: "Bakanlıkların kurulması ne ile yapılır?",
    secenekler: ["Kanun", "Cumhurbaşkanlığı kararnamesi", "Yönetmelik", "İç tüzük"],
    dogru: 1,
  },
  {
    id: 160,
    konu: "Kararnameler",
    soru: "Devlet Denetleme Kurulu hangi anayasa ile gelmiştir?",
    secenekler: ["1961", "1982", "2010", "2017"],
    dogru: 1,
  },
  {
    id: 161,
    konu: "Kararnameler",
    soru: "OHAL kararnameleri Resmi Gazete'de yayımlandığı gün nereye sunulur?",
    secenekler: ["Danıştaya", "Meclisin onayına", "Cumhurbaşkanına", "Anayasa Mahkemesine"],
    dogru: 1,
  },
  {
    id: 162,
    konu: "Kararnameler",
    soru: "OHAL kararnamelerinin yargısal denetimi için hangisi doğrudur?",
    secenekler: [
      "Danıştay denetler",
      "Yargısal denetimi yoktur",
      "Anayasa Mahkemesi denetler",
      "Yargıtay denetler",
    ],
    dogru: 1,
  },
  {
    id: 163,
    konu: "Kararnameler",
    soru: "OHAL kararnameleri (savaş hariç) en geç kaç ay içinde TBMM'de görüşülür?",
    secenekler: ["1 ay", "2 ay", "3 ay", "6 ay"],
    dogru: 2,
  },

  // ---------- Yönetmelik / Kamu Tüzel Kişileri ----------
  {
    id: 164,
    konu: "Yönetmelik",
    soru: "Aşağıdakilerden hangisi yönetmelik çıkarabilir?",
    secenekler: ["Milletvekilleri", "Cumhurbaşkanı, bakanlıklar, kamu tüzel kişileri", "TBMM", "Mahkemeler"],
    dogru: 1,
  },
  {
    id: 165,
    konu: "Kamu Tüzel Kişileri",
    soru: "Kamu tüzel kişiliği ne ile kurulabilir?",
    secenekler: [
      "Sadece kanunla",
      "Kanunla veya Cumhurbaşkanlığı kararnamesiyle",
      "Sadece kararnameyle",
      "Yönetmelikle",
    ],
    dogru: 1,
  },
  {
    id: 166,
    konu: "Yerinden Yönetim",
    soru: "Mahalli idareler (yer yönünden yerinden yönetim) aşağıdakilerden hangisidir?",
    secenekler: [
      "Üniversiteler",
      "İl özel idaresi, belediyeler, köyler",
      "KİT'ler",
      "TRT",
    ],
    dogru: 1,
  },

  // ---------- Genelkurmay / MGK ----------
  {
    id: 167,
    konu: "Ordu",
    soru: "Genelkurmay Başkanı savaşta kimin adına görev yapar?",
    secenekler: ["TBMM", "Cumhurbaşkanı", "Milli Savunma Bakanı", "Kendisi"],
    dogru: 1,
  },
  {
    id: 168,
    konu: "Ordu",
    soru: "Genelkurmay Başkanını kim atar?",
    secenekler: ["TBMM", "Cumhurbaşkanı", "Milli Savunma Bakanı", "Yüksek Askeri Şura"],
    dogru: 1,
  },
  {
    id: 169,
    konu: "Ordu",
    soru: "Genelkurmay Başkanı hangi makama bağlıdır?",
    secenekler: ["Cumhurbaşkanlığı", "Milli Savunma Bakanlığı", "TBMM", "İçişleri Bakanlığı"],
    dogru: 1,
  },
  {
    id: 170,
    konu: "MGK",
    soru: "Milli Güvenlik Kurulu ilk hangi anayasa ile kurulmuştur?",
    secenekler: ["1961", "1982", "1924", "2010"],
    dogru: 0,
  },
  {
    id: 171,
    konu: "MGK",
    soru: "MGK kaç ayda bir toplanır?",
    secenekler: ["1 ayda bir", "2 ayda bir", "3 ayda bir", "6 ayda bir"],
    dogru: 1,
  },
  {
    id: 172,
    konu: "MGK",
    soru: "MGK'ya normalde katılan 4 bakan hangileridir?",
    secenekler: [
      "Adalet, İçişleri, Dışişleri, Milli Savunma",
      "Milli Eğitim, Sağlık, Ulaştırma, Maliye",
      "Adalet, Sağlık, Dışişleri, Hazine",
      "İçişleri, Maliye, Sanayi, Enerji",
    ],
    dogru: 0,
  },
  {
    id: 173,
    konu: "MGK",
    soru: "MGK kararları için hangisi doğrudur?",
    secenekler: [
      "Bağlayıcıdır",
      "Cumhurbaşkanına tavsiye niteliğindedir",
      "Kesindir",
      "Kanun hükmündedir",
    ],
    dogru: 1,
  },

  // ---------- OHAL ----------
  {
    id: 174,
    konu: "OHAL",
    soru: "Cumhurbaşkanı en fazla kaç ay için OHAL ilan edebilir?",
    secenekler: ["3 ay", "6 ay", "1 yıl", "2 ay"],
    dogru: 1,
  },
  {
    id: 175,
    konu: "OHAL",
    soru: "OHAL süresi ilan edildikten sonra hangi organ değiştirebilir/kaldırabilir?",
    secenekler: ["Cumhurbaşkanı", "TBMM", "Anayasa Mahkemesi", "Danıştay"],
    dogru: 1,
  },
  {
    id: 176,
    konu: "OHAL",
    soru: "TBMM, Cumhurbaşkanının önerisiyle OHAL'i her defasında en fazla kaç ay uzatabilir?",
    secenekler: ["2 ay", "3 ay", "4 ay", "6 ay"],
    dogru: 2,
  },

  // ---------- Yargı ----------
  {
    id: 177,
    konu: "Yargı",
    soru: "Hâkim ve savcılar idari görevleri bakımından hangi makama bağlıdır?",
    secenekler: ["Cumhurbaşkanlığı", "Adalet Bakanlığı", "HSK", "Yargıtay"],
    dogru: 1,
  },
  {
    id: 178,
    konu: "Yargı",
    soru: "Askeri mahkeme ne zaman kurulabilir?",
    secenekler: ["Her zaman", "Savaş halinde", "Barışta", "OHAL'de"],
    dogru: 1,
  },
  {
    id: 179,
    konu: "Yargı",
    soru: "İlk derece mahkemesi kararlarının incelendiği bölge mahkemesine ne denir?",
    secenekler: ["Temyiz", "İstinaf (bölge adliye mahkemesi)", "Yargıtay", "Danıştay"],
    dogru: 1,
  },
  {
    id: 180,
    konu: "Yargı",
    soru: "Yargıtay'a başvurma yoluna ne denir?",
    secenekler: ["İstinaf", "Temyiz", "İtiraz", "Karar düzeltme"],
    dogru: 1,
  },
  {
    id: 181,
    konu: "Alternatif Çözüm",
    soru: "Arabuluculuk hangi hukuk dalında uygulanır?",
    secenekler: ["Ceza hukuku", "Özel hukuk", "İdare hukuku", "Anayasa hukuku"],
    dogru: 1,
  },
  {
    id: 182,
    konu: "Alternatif Çözüm",
    soru: "Uyuşmazlığın hakemler tarafından çözülmesine ne denir?",
    secenekler: ["Arabuluculuk", "Tahkim", "Uzlaştırma", "İstinaf"],
    dogru: 1,
  },
  {
    id: 183,
    konu: "Alternatif Çözüm",
    soru: "Uzlaştırma hangi hukuk dalında uygulanır?",
    secenekler: ["Özel hukuk", "Ceza hukuku", "İdare hukuku", "Ticaret hukuku"],
    dogru: 1,
  },

  // ---------- Yüksek Mahkemeler / HSK ----------
  {
    id: 184,
    konu: "Yüksek Mahkemeler",
    soru: "Yargıtay'ın tüm üyelerini kim seçer?",
    secenekler: ["Cumhurbaşkanı", "Hâkimler ve Savcılar Kurulu (HSK)", "TBMM", "Adalet Bakanı"],
    dogru: 1,
  },
  {
    id: 185,
    konu: "Yüksek Mahkemeler",
    soru: "Danıştay üyelerinin 1/4'ünü kim seçer?",
    secenekler: ["TBMM", "Cumhurbaşkanı", "HSK", "Yargıtay"],
    dogru: 1,
  },
  {
    id: 186,
    konu: "Anayasa Mahkemesi",
    soru: "Anayasa Mahkemesi üyelerinden kaçını TBMM seçer?",
    secenekler: ["3", "4", "12", "15"],
    dogru: 0,
  },
  {
    id: 187,
    konu: "Anayasa Mahkemesi",
    soru: "Anayasa Mahkemesi üyelerinden kaçını Cumhurbaşkanı seçer?",
    secenekler: ["3", "4", "12", "15"],
    dogru: 2,
  },
  {
    id: 188,
    konu: "Anayasa Mahkemesi",
    soru: "TBMM'nin seçtiği 3 üyeden kaçı Sayıştay'ın gösterdiği adaylardandır?",
    secenekler: ["1", "2", "3", "Hiçbiri"],
    dogru: 1,
  },
  {
    id: 189,
    konu: "Anayasa Mahkemesi",
    soru: "TBMM'nin seçtiği 3 üyeden 1'i kimin gösterdiği adaydır?",
    secenekler: ["Sayıştay", "Baro başkanları", "Yargıtay", "Danıştay"],
    dogru: 1,
  },
  {
    id: 190,
    konu: "Anayasa Mahkemesi",
    soru: "Anayasa Mahkemesi üyelerinin görev süresi kaç yıldır?",
    secenekler: ["9 yıl", "12 yıl", "4 yıl", "6 yıl"],
    dogru: 1,
  },
  {
    id: 191,
    konu: "Anayasa Mahkemesi",
    soru: "Anayasa Mahkemesi üyeleri kaç yaşında emekli olur?",
    secenekler: ["60", "65", "67", "70"],
    dogru: 1,
  },
  {
    id: 192,
    konu: "Bireysel Başvuru",
    soru: "Anayasa Mahkemesine bireysel başvuru hangi yılda gelmiştir?",
    secenekler: ["1982", "2010", "2017", "1961"],
    dogru: 1,
  },
  {
    id: 193,
    konu: "İdari Yargı",
    soru: "Yönetmeliklerin iptaline hangi mahkeme bakar?",
    secenekler: ["Anayasa Mahkemesi", "Danıştay", "Yargıtay", "İdare Mahkemesi"],
    dogru: 1,
  },

  // ---------- AYM Denetimi ----------
  {
    id: 194,
    konu: "Anayasa Mahkemesi",
    soru: "Anayasa Mahkemesi aşağıdakilerden hangisini denetlemez?",
    secenekler: [
      "Kanunlar",
      "Yönetmelikler",
      "Cumhurbaşkanlığı kararnameleri",
      "TBMM İç Tüzüğü",
    ],
    dogru: 1,
  },
  {
    id: 195,
    konu: "Anayasa Mahkemesi",
    soru: "Anayasa değişikliklerini AYM hangi bakımdan denetler?",
    secenekler: ["Sadece esas", "Sadece şekil", "Hem şekil hem esas", "Denetlemez"],
    dogru: 1,
  },
  {
    id: 196,
    konu: "Anayasa Mahkemesi",
    soru: "AYM'de partinin kapatılması, hazineden yoksun bırakma ve anayasa değişikliği iptali için hangi çoğunluk gerekir?",
    secenekler: ["Salt çoğunluk", "2/3 çoğunluk", "Basit çoğunluk", "Oybirliği"],
    dogru: 1,
  },
  {
    id: 197,
    konu: "Norm Denetimi",
    soru: "Bir mahkemenin uygulanacak kanunu anayasaya aykırı görüp AYM'ye başvurmasına ne denir?",
    secenekler: ["Soyut norm denetimi", "Somut norm denetimi (itiraz)", "Bireysel başvuru", "İptal davası"],
    dogru: 1,
  },
  {
    id: 198,
    konu: "Norm Denetimi",
    soru: "Somut norm denetiminde mahkeme davayı en fazla kaç ay durdurabilir?",
    secenekler: ["3 ay", "5 ay", "6 ay", "1 yıl"],
    dogru: 1,
  },
  {
    id: 199,
    konu: "Norm Denetimi",
    soru: "AYM itirazı reddederse, aynı konuda kaç yıl geçmeden tekrar başvurulamaz?",
    secenekler: ["5 yıl", "10 yıl", "3 yıl", "1 yıl"],
    dogru: 1,
  },
  {
    id: 200,
    konu: "Norm Denetimi",
    soru: "Yasa çıktıktan sonra CB ve milletvekillerinin AYM'ye başvurmasına ne denir?",
    secenekler: ["Somut norm denetimi", "Soyut norm denetimi (iptal davası)", "Bireysel başvuru", "İtiraz"],
    dogru: 1,
  },

  // ---------- AYM Süreleri ----------
  {
    id: 201,
    konu: "AYM Süreleri",
    soru: "Kanunlarda şekil bakımından iptal davası açma süresi kaç gündür?",
    secenekler: ["10 gün", "60 gün", "30 gün", "15 gün"],
    dogru: 0,
  },
  {
    id: 202,
    konu: "AYM Süreleri",
    soru: "Kanunlarda esas bakımından iptal davası açma süresi kaç gündür?",
    secenekler: ["10 gün", "60 gün", "30 gün", "90 gün"],
    dogru: 1,
  },
  {
    id: 203,
    konu: "AYM Süreleri",
    soru: "İç tüzük ve kararnamelerde iptal davası süresi kaç gündür?",
    secenekler: ["10 gün", "30 gün", "60 gün", "90 gün"],
    dogru: 2,
  },
  {
    id: 204,
    konu: "İptal Davası",
    soru: "AYM'de iptal davasını kimler açabilir?",
    secenekler: [
      "Herkes",
      "CB, 120 milletvekili ve en yüksek 2 parti grubu",
      "Sadece Cumhurbaşkanı",
      "Sadece mahkemeler",
    ],
    dogru: 1,
  },

  // ---------- Yüce Divan ----------
  {
    id: 205,
    konu: "Yüce Divan",
    soru: "Aşağıdakilerden hangisi Yüce Divan'da yargılanmaz?",
    secenekler: [
      "Cumhurbaşkanı",
      "Bakanlar",
      "Milletvekilleri",
      "Genelkurmay Başkanı",
    ],
    dogru: 2,
  },
  {
    id: 206,
    konu: "AYM",
    soru: "AYM iptal hükmünün yürürlüğe girmesini en fazla ne kadar erteleyebilir?",
    secenekler: ["6 ay", "1 yıl", "2 yıl", "3 ay"],
    dogru: 1,
  },

  // ---------- İnkılap Kanunları ----------
  {
    id: 207,
    konu: "İnkılap Kanunları",
    soru: "Aşağıdakilerden hangisi yargı denetimine kapalı inkılap kanunlarından DEĞİLDİR?",
    secenekler: [
      "Şapka Kanunu",
      "Tekke ve zaviyelerin kapatılması",
      "Tevhid-i Tedrisat Kanunu",
      "Belediye Kanunu",
    ],
    dogru: 3,
  },

  // ---------- Danıştay / HSK ----------
  {
    id: 208,
    konu: "Danıştay",
    soru: "Danıştay düşüncelerini kaç ay içinde bildirmek zorundadır?",
    secenekler: ["1 ay", "2 ay", "3 ay", "6 ay"],
    dogru: 1,
  },
  {
    id: 209,
    konu: "HSK",
    soru: "Hâkimler ve Savcılar Kurulu kaç üyeden ve kaç daireden oluşur?",
    secenekler: ["11 üye 2 daire", "13 üye 2 daire", "13 üye 3 daire", "15 üye 2 daire"],
    dogru: 1,
  },
  {
    id: 210,
    konu: "HSK",
    soru: "HSK üyeleri kaç yıl için seçilir?",
    secenekler: ["2 yıl", "4 yıl", "6 yıl", "9 yıl"],
    dogru: 1,
  },
  {
    id: 211,
    konu: "HSK",
    soru: "Hâkimlerin meslekten çıkarılması kararına karşı hangisi doğrudur?",
    secenekler: [
      "Yargı yolu kapalıdır",
      "Yargı yolu açıktır (diğer kararlara kapalı)",
      "Sadece itiraz edilebilir",
      "Cumhurbaşkanı karar verir",
    ],
    dogru: 1,
  },

  // ---------- İdare / Anayasal Kuruluşlar ----------
  {
    id: 212,
    konu: "İdare",
    soru: "Cumhurbaşkanına ekonomi alanında görüş bildiren kurum hangisidir?",
    secenekler: ["Sayıştay", "Ekonomik ve Sosyal Konsey", "Danıştay", "DPT"],
    dogru: 1,
  },
  {
    id: 213,
    konu: "Anayasal Kuruluşlar",
    soru: "Aşağıdakilerden hangisi anayasada yer alan kuruluşlardan biri DEĞİLDİR?",
    secenekler: [
      "TRT ve üniversiteler",
      "Belediyeler ve köy",
      "YÖK ve RTÜK",
      "Atatürk Kültür, Dil ve Tarih Yüksek Kurumu",
    ],
    dogru: 2,
  },
  {
    id: 214,
    konu: "Mahalli İdareler",
    soru: "Mahalli idareler kimin izniyle birlik kurabilir?",
    secenekler: ["TBMM", "Cumhurbaşkanı", "İçişleri Bakanı", "Vali"],
    dogru: 1,
  },
  {
    id: 215,
    konu: "İdarenin Bütünlüğü",
    soru: "Merkezi idarenin yerinden yönetim kuruluşları üzerindeki denetimine ne denir?",
    secenekler: ["Hiyerarşi", "İdari vesayet", "Yetki genişliği", "Yerinden yönetim"],
    dogru: 1,
  },
  {
    id: 216,
    konu: "İdare",
    soru: "Yetki genişliği ilkesi ilk hangi anayasada yer almıştır?",
    secenekler: ["1961", "1982", "1924", "1921"],
    dogru: 1,
  },
  {
    id: 217,
    konu: "İdare",
    soru: "En yüksek devlet memuru kimdir?",
    secenekler: ["Vali", "Cumhurbaşkanlığı İdari İşler Başkanı (genel sekreteri)", "Müsteşar", "Kaymakam"],
    dogru: 1,
  },

  // ---------- Yüksek Askeri Şura ----------
  {
    id: 218,
    konu: "Yüksek Askeri Şura",
    soru: "Yüksek Askeri Şura yılda kaç kez toplanır?",
    secenekler: ["1 kez", "2 kez", "3 kez", "4 kez"],
    dogru: 0,
  },

  // ---------- Taşra Yönetimi ----------
  {
    id: 219,
    konu: "Taşra Yönetimi",
    soru: "İl ve ilçeler ne ile kurulur?",
    secenekler: ["Cumhurbaşkanlığı kararnamesi", "Kanun", "Yönetmelik", "Bakanlık kararı"],
    dogru: 1,
  },
  {
    id: 220,
    konu: "Taşra Yönetimi",
    soru: "İlin başındaki mülki idare amiri kimdir?",
    secenekler: ["Kaymakam", "Vali", "Belediye Başkanı", "Muhtar"],
    dogru: 1,
  },
  {
    id: 221,
    konu: "Taşra Yönetimi",
    soru: "İlçenin başındaki mülki idare amiri kimdir?",
    secenekler: ["Vali", "Kaymakam", "Muhtar", "Belediye Başkanı"],
    dogru: 1,
  },
  {
    id: 222,
    konu: "İl Özel İdaresi",
    soru: "İl özel idaresinin karar organı hangisidir?",
    secenekler: ["Vali", "İl Genel Meclisi", "İl Encümeni", "İl İdare Kurulu"],
    dogru: 1,
  },
  {
    id: 223,
    konu: "İl Özel İdaresi",
    soru: "İl özel idaresinin müzakere ve danışma organı hangisidir?",
    secenekler: ["İl Genel Meclisi", "İl Encümeni", "Vali", "İl İdare Kurulu"],
    dogru: 1,
  },
  {
    id: 224,
    konu: "Belediye",
    soru: "Belediyenin ana karar organı hangisidir?",
    secenekler: ["Belediye Başkanı", "Belediye Meclisi", "Belediye Encümeni", "Vali"],
    dogru: 1,
  },
  {
    id: 225,
    konu: "Belediye",
    soru: "Belediyenin danışma organı hangisidir?",
    secenekler: ["Belediye Meclisi", "Belediye Encümeni", "Belediye Başkanı", "Muhtar"],
    dogru: 1,
  },
  {
    id: 226,
    konu: "Köy",
    soru: "Köyün karar organı hangisidir?",
    secenekler: ["Muhtar", "Köy İhtiyar Meclisi", "Köy Derneği", "Kaymakam"],
    dogru: 1,
  },
  {
    id: 227,
    konu: "Köy",
    soru: "Köyün danışma organı hangisidir?",
    secenekler: ["Köy İhtiyar Meclisi", "Köy Derneği", "Muhtar", "İl Genel Meclisi"],
    dogru: 1,
  },
  {
    id: 228,
    konu: "Belediye Başkanı",
    soru: "Belediye başkanını görevden uzaklaştırma (açığa alma) yetkisi kimdedir?",
    secenekler: ["Cumhurbaşkanı", "İçişleri Bakanı", "Vali", "Danıştay"],
    dogru: 1,
  },
  {
    id: 229,
    konu: "Belediye Başkanı",
    soru: "Belediye başkanının görevine son verme yetkisi kimdedir?",
    secenekler: ["İçişleri Bakanı", "Danıştay", "Cumhurbaşkanı", "Vali"],
    dogru: 1,
  },
  {
    id: 230,
    konu: "Mahalli İdareler",
    soru: "Belediye kurulabilmesi için nüfus en az kaç olmalıdır?",
    secenekler: ["2000", "5000", "500", "10000"],
    dogru: 1,
  },
  {
    id: 231,
    konu: "Mahalli İdareler",
    soru: "Köy nüfusu ne kadarın altında olur?",
    secenekler: ["5000", "2000", "500", "1000"],
    dogru: 1,
  },
  {
    id: 232,
    konu: "Mahalli İdareler",
    soru: "Mahalle kurulabilmesi için nüfus en az kaç olmalıdır?",
    secenekler: ["500", "2000", "5000", "1000"],
    dogru: 0,
  },
  {
    id: 233,
    konu: "Mahalle",
    soru: "Mahallenin kamu tüzel kişiliği var mıdır?",
    secenekler: ["Vardır", "Yoktur", "Kısmen vardır", "Valinin iznine bağlıdır"],
    dogru: 1,
  },
  {
    id: 234,
    konu: "Büyükşehir",
    soru: "Büyükşehirlerde aşağıdakilerden hangisi bulunmaz?",
    secenekler: [
      "Belediye meclisi",
      "İl özel idaresi, köy ve belde belediyesi",
      "Belediye encümeni",
      "Belediye başkanı",
    ],
    dogru: 1,
  },
  {
    id: 235,
    konu: "Muhtar",
    soru: "Muhtar seçilmek için ilkokul mezuniyeti aranır mı?",
    secenekler: ["Evet aranır", "Aranmaz", "Sadece köyde aranır", "Sadece mahallede aranır"],
    dogru: 1,
  },

  // ---------- İdare Hukuku Kavramları ----------
  {
    id: 236,
    konu: "İdare Hukuku",
    soru: "Savaş gibi durumlarda kamu görevlisi olmayan kişinin kamu görevlisiymiş gibi iş yapmasına ne denir?",
    secenekler: ["Fiili yol", "Fiili memur teorisi", "Usulde paralellik", "Yetki paralelliği"],
    dogru: 1,
  },
  {
    id: 237,
    konu: "İdare Hukuku",
    soru: "İdarenin hukuka aykırı biçimde temel haklarımızı ihlal etmesine ne denir?",
    secenekler: ["Fiili yol", "Fiili memur teorisi", "İdari eylem", "Vesayet"],
    dogru: 0,
  },
  {
    id: 238,
    konu: "İdare Hukuku",
    soru: "Bir işlemin oluştuğu şekilde kaldırılması/değiştirilmesi gerektiğini belirten ilke hangisidir?",
    secenekler: ["Yetki paralelliği", "Usulde paralellik", "Fiili yol", "Hiyerarşi"],
    dogru: 1,
  },
  {
    id: 239,
    konu: "İdare Hukuku",
    soru: "Bir işi kim yaptıysa kaldırmaya da onun yetkili olması ilkesi hangisidir?",
    secenekler: ["Usulde paralellik", "Yetki paralelliği", "Fiili yol", "İdari vesayet"],
    dogru: 1,
  },

  // ---------- Kamulaştırma ----------
  {
    id: 240,
    konu: "Kamulaştırma",
    soru: "Kamulaştırma hangi mallarda yapılır?",
    secenekler: ["Taşınır mallarda", "Taşınmaz mallarda", "Her tür malda", "Sadece parada"],
    dogru: 1,
  },
  {
    id: 241,
    konu: "Kamulaştırma",
    soru: "Kamulaştırmada taksitlendirme en fazla kaç yıl olabilir?",
    secenekler: ["3 yıl", "5 yıl", "10 yıl", "2 yıl"],
    dogru: 1,
  },
  {
    id: 242,
    konu: "Kamulaştırma",
    soru: "Küçük çiftçinin kamulaştırılan malı nasıl ödenir?",
    secenekler: ["Taksitle", "Her şekilde peşin", "5 yılda", "Bedelsiz"],
    dogru: 1,
  },

  // ---------- Kamu Hizmeti ----------
  {
    id: 243,
    konu: "Kamu Hizmeti",
    soru: "Aşağıdakilerden hangisi kamu hizmetine egemen ilkelerden biri DEĞİLDİR?",
    secenekler: ["Süreklilik", "Değişkenlik (uyarlama)", "Kâr amacı", "Tarafsızlık"],
    dogru: 2,
  },
  {
    id: 244,
    konu: "Kamu Hizmeti Usulleri",
    soru: "İdarenin bir hizmeti kendi personeli, araç ve gereçleriyle yapmasına ne denir?",
    secenekler: ["İltizam", "Emanet usulü", "İmtiyaz", "Ruhsat"],
    dogru: 1,
  },
  {
    id: 245,
    konu: "Kamu Hizmeti Usulleri",
    soru: "Özel okul gibi yerlerin kamu hizmeti yapmasına ne denir?",
    secenekler: ["Emanet usulü", "Ruhsat usulü", "İltizam", "İmtiyaz"],
    dogru: 1,
  },
  {
    id: 246,
    konu: "Kamu Hizmeti Usulleri",
    soru: "Para karşılığı bir kamu işinin başkasına verilmesine ne denir?",
    secenekler: ["İltizam", "İmtiyaz", "Emanet", "Ruhsat"],
    dogru: 0,
  },
  {
    id: 247,
    konu: "Kamu Hizmeti Usulleri",
    soru: "Bir kamu hizmetinin özel kişi tarafından kurulup işletilmesi ve kâr/zararın ona ait olmasına ne denir?",
    secenekler: ["İltizam", "İmtiyaz usulü", "Emanet", "Ruhsat"],
    dogru: 1,
  },
  {
    id: 248,
    konu: "Kamu Hizmeti Usulleri",
    soru: "İmtiyaz sözleşmesinde Danıştay görüşünü kaç ay içinde bildirir?",
    secenekler: ["1 ay", "2 ay", "3 ay", "6 ay"],
    dogru: 1,
  },
  {
    id: 249,
    konu: "İdare Hukuku",
    soru: "Taşınır malların olağanüstü durumlarda idarece edinilmesine ne denir?",
    secenekler: ["Kamulaştırma", "İstimval", "İstimlak", "El koyma"],
    dogru: 1,
  },
  {
    id: 250,
    konu: "İdare Hukuku",
    soru: "İdarenin maddi nitelikteki faaliyetlerine ne denir?",
    secenekler: ["İdari işlem", "İdari eylem", "İdari sözleşme", "İdari karar"],
    dogru: 1,
  },

  // ---------- İdari İşlemin Kaldırılması ----------
  {
    id: 251,
    konu: "İdari İşlem",
    soru: "İdarenin hukuka aykırı bir işlemi geçmişe etkili olarak kaldırmasına ne denir?",
    secenekler: ["Kaldırma (ilga)", "Geri alma", "İptal", "Tam yargı"],
    dogru: 1,
  },
  {
    id: 252,
    konu: "İdari Yargı",
    soru: "İdare hukukundaki tazminat davasına ne denir?",
    secenekler: ["İptal davası", "Tam yargı davası", "Tespit davası", "İnşai dava"],
    dogru: 1,
  },

  // ---------- Devlet Memurları Kanunu ----------
  {
    id: 253,
    konu: "Memur Hukuku",
    soru: "Devlet Memurları Kanunu'nun 3 temel ilkesi hangisidir?",
    secenekler: [
      "Eşitlik, liyakat, sınıflandırma",
      "Sınıflandırma, kariyer, liyakat",
      "Kariyer, eşitlik, tarafsızlık",
      "Liyakat, süreklilik, eşitlik",
    ],
    dogru: 1,
  },
  {
    id: 254,
    konu: "Memur Hukuku",
    soru: "Devlet Memurları Kanunu'na göre istihdam türlerinden biri DEĞİLDİR?",
    secenekler: ["Memur", "Sözleşmeli personel", "İşçi", "Serbest meslek"],
    dogru: 3,
  },
  {
    id: 255,
    konu: "Memur Hukuku",
    soru: "Aday memur başarısız olursa kaç yıl tekrar başvuramaz?",
    secenekler: ["1 yıl", "3 yıl", "5 yıl", "2 yıl"],
    dogru: 1,
  },
  {
    id: 256,
    konu: "Memur Hukuku",
    soru: "Atanıp mazeretsiz göreve başlamayan kişi kaç yıl başvuramaz?",
    secenekler: ["1 yıl", "3 yıl", "5 yıl", "6 ay"],
    dogru: 0,
  },
  {
    id: 257,
    konu: "İstisnai Memurluk",
    soru: "Aşağıdakilerden hangisi istisnai memurluk DEĞİLDİR?",
    secenekler: ["Vali", "Büyükelçi", "Kaymakam", "Bakan yardımcısı"],
    dogru: 2,
  },
  {
    id: 258,
    konu: "Memur Yasakları",
    soru: "Aşağıdakilerden hangisi memurun yasakları arasındadır?",
    secenekler: ["İzin kullanmak", "Grev", "Mal bildirimi", "Sendika üyeliği"],
    dogru: 1,
  },
  {
    id: 259,
    konu: "Memur Hukuku",
    soru: "Mal bildirimi hangi yıllarda yapılır?",
    secenekler: [
      "1 ve 6 ile biten yıllarda",
      "0 ve 5 ile biten yıllarda",
      "Her yıl",
      "3 ve 8 ile biten yıllarda",
    ],
    dogru: 1,
  },
  {
    id: 260,
    konu: "Memur İzinleri",
    soru: "Eşi doğum yapan babaya kaç gün izin verilir?",
    secenekler: ["5 gün", "10 gün", "15 gün", "3 gün"],
    dogru: 1,
  },
  {
    id: 261,
    konu: "Analık İzni",
    soru: "Analık izni toplam kaç haftadır (doğum öncesi 8 + sonrası 16)?",
    secenekler: ["16 hafta", "24 hafta", "20 hafta", "18 hafta"],
    dogru: 1,
  },
  {
    id: 262,
    konu: "Analık İzni",
    soru: "Çoğul gebelikte doğum öncesine kaç hafta daha eklenir?",
    secenekler: ["1 hafta", "2 hafta", "3 hafta", "4 hafta"],
    dogru: 1,
  },

  // ---------- Disiplin Cezaları ----------
  {
    id: 263,
    konu: "Disiplin Cezaları",
    soru: "Devlet memurluğundan çıkarma cezasını hangi kurul verir?",
    secenekler: ["Disiplin amiri", "Yüksek Disiplin Kurulu", "Atamaya yetkili amir", "Vali"],
    dogru: 1,
  },
  {
    id: 264,
    konu: "Disiplin Cezaları",
    soru: "Kademe ilerlemesinin durdurulması cezasını kim verir?",
    secenekler: ["Disiplin amiri", "Atamaya yetkili amir", "Yüksek Disiplin Kurulu", "Vali"],
    dogru: 1,
  },
  {
    id: 265,
    konu: "Disiplin Cezaları",
    soru: "Aşağıdakilerden hangisi disiplin amirinin verebileceği cezalardandır?",
    secenekler: [
      "Devlet memurluğundan çıkarma",
      "Uyarma, kınama, aylıktan kesme",
      "Kademe ilerlemesinin durdurulması",
      "Meslekten men",
    ],
    dogru: 1,
  },
  {
    id: 266,
    konu: "Disiplin Cezaları",
    soru: "Kademe ilerlemesinin durdurulması en az ve en çok kaç yıldır?",
    secenekler: ["En az 1 en çok 3 yıl", "En az 2 en çok 5 yıl", "En az 1 en çok 5 yıl", "En az 3 en çok 6 yıl"],
    dogru: 0,
  },
  {
    id: 267,
    konu: "Disiplin Cezaları",
    soru: "Uyarma ve kınama cezaları kaç yıl sonra sicilden silinebilir?",
    secenekler: ["3 yıl", "5 yıl", "10 yıl", "1 yıl"],
    dogru: 1,
  },
  {
    id: 268,
    konu: "Disiplin Cezaları",
    soru: "Aylıktan kesme ve kademe ilerlemesinin durdurulması cezaları kaç yıl sonra sicilden silinebilir?",
    secenekler: ["5 yıl", "10 yıl", "3 yıl", "15 yıl"],
    dogru: 1,
  },

  // ---------- Uzaklaştırma ----------
  {
    id: 269,
    konu: "Görevden Uzaklaştırma",
    soru: "Aşağıdakilerden hangisi görevden uzaklaştırma yetkisine sahip DEĞİLDİR?",
    secenekler: ["Atamaya yetkili amir", "Bakanlık müfettişi", "Muhtar", "Vali ve kaymakam"],
    dogru: 2,
  },
  {
    id: 270,
    konu: "Görevden Uzaklaştırma",
    soru: "Görevden uzaklaştırma süresi en fazla kaç aydır?",
    secenekler: ["1 ay", "2 ay", "3 ay", "6 ay"],
    dogru: 2,
  },
  {
    id: 271,
    konu: "Görevden Uzaklaştırma",
    soru: "Ceza davasıyla ilgili uzaklaştırma kaç ayda bir gözden geçirilir?",
    secenekler: ["1 ay", "2 ay", "3 ay", "6 ay"],
    dogru: 1,
  },
  {
    id: 272,
    konu: "Memur Hukuku",
    soru: "Kadronun kaldırılması memurluğu sona erdirir mi?",
    secenekler: ["Evet erdirir", "Hayır erdirmez", "Kısmen", "1 yıl sonra erdirir"],
    dogru: 1,
  },

  // ---------- İstifa ----------
  {
    id: 273,
    konu: "İstifa",
    soru: "Devir teslim yapmadan görevden ayrılan memur kaç yıl geçmeden geri dönemez?",
    secenekler: ["1 yıl", "2 yıl", "3 yıl", "6 ay"],
    dogru: 2,
  },
  {
    id: 274,
    konu: "İstifa",
    soru: "OHAL zamanı izinsiz görevi bırakan memur ne zaman geri dönebilir?",
    secenekler: ["1 yıl sonra", "3 yıl sonra", "6 ay sonra", "Bir daha hiç dönemez"],
    dogru: 3,
  },

  // ---------- Uluslararası ----------
  {
    id: 275,
    konu: "Uluslararası Hukuk",
    soru: "Temel hakları (negatif, pozitif, aktif statü) ayıran düşünür kimdir?",
    secenekler: ["Rousseau", "Georg Jellinek", "Montesquieu", "John Locke"],
    dogru: 1,
  },
  {
    id: 276,
    konu: "Uluslararası Hukuk",
    soru: "Birleşmiş Milletler'in yargı organı hangisidir?",
    secenekler: ["AİHM", "Uluslararası Adalet Divanı", "Lahey Ceza Divanı", "Avrupa Konseyi"],
    dogru: 1,
  },
  {
    id: 277,
    konu: "Uluslararası Hukuk",
    soru: "BM Güvenlik Konseyi'nin 5 daimi üyesi hangileridir?",
    secenekler: [
      "Fransa, İngiltere, Rusya, Çin, ABD",
      "Almanya, Japonya, ABD, Rusya, Çin",
      "Fransa, İtalya, ABD, Çin, Rusya",
      "İngiltere, Almanya, ABD, Çin, Japonya",
    ],
    dogru: 0,
  },
  {
    id: 278,
    konu: "AİHM",
    soru: "AİHM yargıçlarını kim seçer?",
    secenekler: [
      "Avrupa Komisyonu",
      "Avrupa Konseyi Parlamenter Meclisi",
      "Avrupa Parlamentosu",
      "BM Genel Kurulu",
    ],
    dogru: 1,
  },
  {
    id: 279,
    konu: "Temel Haklar",
    soru: "Aşağıdakilerden hangisi birinci kuşak haklardandır?",
    secenekler: [
      "Sağlık hakkı",
      "Kişi özgürlüğü, seçme-seçilme, mülkiyet",
      "Çevre hakkı",
      "Sosyal güvenlik hakkı",
    ],
    dogru: 1,
  },
  {
    id: 280,
    konu: "AİHM",
    soru: "AİHM'e başvurmak için iç hukuk yolları tükendikten sonra kaç ay içinde başvurulur?",
    secenekler: ["6 ay", "4 ay", "3 ay", "1 yıl"],
    dogru: 1,
  },

  // ---------- Ek sorular ----------
  {
    id: 281,
    konu: "Meclis Soruşturması",
    soru: "Cumhurbaşkanı yardımcıları ve bakanlar görevleriyle ilgili suç işlerse hangi denetim yolu uygulanır?",
    secenekler: ["Genel görüşme", "Meclis soruşturması", "Gensoru", "Yazılı soru"],
    dogru: 1,
  },
  {
    id: 282,
    konu: "Yasama",
    soru: "TBMM Genel Kurulundaki görüşmeler nasıldır ve nerede yayımlanır?",
    secenekler: [
      "Gizlidir, yayımlanmaz",
      "Açıktır ve Tutanak Dergisinde yayımlanır",
      "Gizlidir, sadece üyeler görür",
      "Açıktır ama yayımlanmaz",
    ],
    dogru: 1,
  },
  {
    id: 283,
    konu: "Savaş İlanı",
    soru: "Savaş ilanı yetkisi kime aittir?",
    secenekler: ["Cumhurbaşkanı", "TBMM", "MGK", "Genelkurmay"],
    dogru: 1,
  },
  {
    id: 284,
    konu: "Bireysel Başvuru",
    soru: "Bireysel başvuru yapıldığında partiyle ilişki ne olur?",
    secenekler: ["Devam eder", "Askıya alınır", "Sona erer", "Etkilenmez"],
    dogru: 1,
  },
  {
    id: 285,
    konu: "AYM Toplantı",
    soru: "AYM'de genel kurul (10 üye) hangi çoğunlukla karar alır?",
    secenekler: ["2/3 çoğunluk", "Salt çoğunluk", "Basit çoğunluk", "Oybirliği"],
    dogru: 1,
  },
  {
    id: 286,
    konu: "Siyasi Partiler",
    soru: "Partisi kapatılan milletvekilinin vekilliği ne olur?",
    secenekler: [
      "Sona erer",
      "Bağımsız olarak devam eder",
      "Askıya alınır",
      "3 yıl donar",
    ],
    dogru: 1,
  },
  {
    id: 287,
    konu: "Boşalan Milletvekilliği",
    soru: "Bir il veya ilçede hiç milletvekili kalmazsa kaç gün içinde seçime gidilir?",
    secenekler: ["60 gün", "90 gün", "30 gün", "45 gün"],
    dogru: 1,
  },
  {
    id: 288,
    konu: "AYM Bireysel Başvuru",
    soru: "AYM'de bireysel başvuruyu kaç üyeli kurul salt çoğunlukla karara bağlar?",
    secenekler: ["10 üye", "4 üye", "3 üye", "7 üye"],
    dogru: 1,
  },
  {
    id: 289,
    konu: "Yüce Divan",
    soru: "Yüce Divan kararlarına karşı hangi yol açıktır?",
    secenekler: [
      "Temyiz",
      "Yeniden inceleme başvurusu",
      "İstinaf",
      "Hiçbir yol yoktur",
    ],
    dogru: 1,
  },
  {
    id: 290,
    konu: "Anayasa Değişikliği Denetimi",
    soru: "Kanun, CB kararnamesi ve iç tüzükte AYM hangi denetimi yapar?",
    secenekler: [
      "Sadece şekil denetimi",
      "Hem şekil hem esas denetimi",
      "Sadece esas denetimi",
      "Denetim yapmaz",
    ],
    dogru: 1,
  },
]
